[WIP] Adding acoustic modeling scripts for opensat competition
kaldi-asr/kaldi pull request #4328
Opened 2020-11-11 23:54 UTC by aarora8

To do:
Some more cleaning and testing and adding results and readme file.

2020-11-12 20:45 UTC, jtrmal requested changes
Hi, I've went only throught less than half of the files -- I think most of the files should be relative symlinks (i.e. redirecting to something like ../../ami/s5/local/ )
Added some other comments as well

2020-11-12 20:45 UTC, jtrmal commented on egs/opensat_20/s5/cmd.sh
> +export cuda_cmd="queue.pl --gpu 1 --mem 20G"
I think you can remove this variable -- we are not using nnet1 anywhere

2020-11-12 20:45 UTC, jtrmal commented on egs/opensat_20/s5/cmd.sh
> +#export decode_cmd="queue.pl -P inf_hcrc_cstr_nst  -l h_rt=05:00:00 -pe memory-2G 4"
please remove

2020-11-12 20:45 UTC, jtrmal commented on egs/opensat_20/s5/local/ami_ihm_data_prep.sh
> +#!/usr/bin/env bash
perhaps symlink to AMI instead of copy?

2020-11-12 20:45 UTC, jtrmal commented on egs/opensat_20/s5/local/ami_ihm_scoring_data_prep.sh
> +#!/usr/bin/env bash
again -- symlink is preferable to copy, if possible

2020-11-12 20:45 UTC, jtrmal commented on egs/opensat_20/s5/local/ami_split_REAMDE.txt
> +The splits in this directory follow the official AMI Corpus Full-ASR split
the file has typo in it's name -- REAMDE instead of README

2020-11-12 20:45 UTC, jtrmal commented on egs/opensat_20/s5/local/ami_split_segments.pl
> +#!/usr/bin/env perl
symlink?

2020-11-12 20:45 UTC, jtrmal commented on egs/opensat_20/s5/local/ami_text_prep.sh
> +#!/usr/bin/env bash
symlink?

2020-11-12 20:45 UTC, jtrmal commented on egs/opensat_20/s5/local/ami_xml2text.sh
> +#!/usr/bin/env bash
symlink?

2020-11-12 20:45 UTC, jtrmal commented on egs/opensat_20/s5/local/analysis/get_high_error_utterance.py
> +#!/usr/bin/env python3
insert license and author (c)

2020-11-12 20:45 UTC, jtrmal commented on egs/opensat_20/s5/local/analysis/get_high_error_utterance.py
> +text_path = '/Users/ashisharora/safet/per_utt'
this should be probably command line paramete

2020-11-12 20:45 UTC, jtrmal commented on egs/opensat_20/s5/local/create_large_lexicon.sh
> +  cp -r /export/c05/aarora8/kaldi2/egs/icsisafet/s5/data/local/dict_nosp /export/c05/aarora8/kaldi2/egs/icsisafet/s5/data/local/dict_nosp_3
probably should not be here... (absolute paths are not useful anywhere else)

2020-11-12 20:45 UTC, jtrmal commented on egs/opensat_20/s5/local/create_large_lexicon.sh
> +  cp /export/c05/aarora8/kaldi2/egs/icsisafet/s5/meta_dexp/kws_exp/data/local/dict_nosp_3/lexicon.txt /export/c05/aarora8/kaldi2/egs/icsisafet/s5/data/local/dict_nosp_3/
ditto

2020-11-12 20:45 UTC, jtrmal commented on egs/opensat_20/s5/local/icsi_agree_words.sh
> +#!/bin/bash
symlink?

2020-11-24 18:14 UTC, aarora8 commented
Thank you for the review, I made the changes as suggested in the review.

2021-01-09 16:00 UTC, aarora8 commented
closing it since changes already part of kaldi/master via https://github.com/kaldi-asr/kaldi/pull/4367

2021-01-09 16:00 UTC, closed without merging