SRLIM file download process
kaldi-asr/kaldi pull request #4624
Opened 2021-09-05 21:38 UTC by jlalfonso21

running the `install_srlim.sh` does not longer needs to download manually the file and rename it. Provide your data as you do in the web and the file will be downloaded on current folder with the format required.

This helps users with no access to a web browser when working on the installation.

2021-09-06 03:26 UTC, danpovey commented
Cool, I assume you tested this?

2021-09-06 04:06 UTC, jlalfonso21 commented
Yes i tested it, only requirements for the changes is `curl` installed on the system and pass 3 args to the script

2021-09-06 04:32 UTC, danpovey commented
Hm, I notice that curl is not currently used in the install/ directory.  I think it might need to be added to the dependencies in `check_dependencies.sh`-- assuming we can't easily use wget, since that is already a dependency.
That would require checking what the package name is on Red Hat and Debian distributions.  If it's simply 'curl', then it can be added on the same line that wget is on.

2021-09-06 04:47 UTC, jlalfonso21 commented
ok, let me update the code to use `wget` instead, so no more dependencies will be added

2021-09-06 04:47 UTC, danpovey commented
Thanks!

On Mon, Sep 6, 2021 at 12:47 PM Jorge Luis Alfonso ***@***.***>
wrote:

> ok, let me update the code to use wget instead, so no more dependencies
> will be added
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/kaldi-asr/kaldi/pull/4624#issuecomment-913335501>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAZFLO6DKPUZBL6ESDNTKE3UARBVHANCNFSM5DPG6A5A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-06 14:52 UTC, jlalfonso21 commented
Ready to use `wget` now, I tested it twice now, all seems to be fine. I keep aware for any problems

2021-09-06 21:01 UTC, kkm000 requested changes

2021-09-08 16:07 UTC, jlalfonso21 commented on tools/extras/install_srilm.sh
>  ! which gawk 2>/dev/null && \
It is done, thanks for your suggestions

2021-09-08 21:32 UTC, kkm000 approved these changes

2021-09-08 21:35 UTC, kkm000 commented
LGTM, thanks! That's a cool idea, really--I could never download SRILM to a headless machine directly. Merging now.

2021-09-08 21:43 UTC, merged

2022-07-26 13:34 UTC, imzakria commented
srilm is not available on this link now: http://www.speech.sri.com/projects/srilm/srilm_download.php

Is there any alternative way of installing it?

2022-07-26 14:45 UTC, jtrmal commented
no other way. Looks like some intermittent issues, maybe they will fix it.
y.

On Tue, Jul 26, 2022 at 9:34 AM Zakria ***@***.***> wrote:

> srilm is not available on this link now:
> http://www.speech.sri.com/projects/srilm/srilm_download.php
>
> Is there any alternative way of installing it?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kaldi-asr/kaldi/pull/4624#issuecomment-1195491840>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACUKYX7MXLQ2PNXWYB6VDDTVV7SOVANCNFSM5DPG6A5A>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>