Updata annotation v.2
kaldi-asr/kaldi pull request #4707
Opened 2022-03-09 14:10 UTC by HuangruiChu

For the monophone training, I think it only uses Delta. While for tri1 and tri2, Delta+Delta-Delta  (first triphone pass) is used. I also make it clear what is [LDA+MLLT (second triphone pass)] and [LDA+MLLT+SAT (third triphone pass)]

2022-04-15 19:17 UTC, kkm000 requested changes
Thank you for improving our commentary! It's really a lot of dirty work, but does support our general code quality, and is really appreciated. Speaking of scripts, and assuming you want to contribute more to the spring cleanup, I think that the commentary that needs the most attention is in the two common directory subtrees `egs/wsj/s5/{utils,steps}`. Individual recipes—all other files under `egs/`, essentially—are too numerous to go through systematically, and are not read as often. A `run.sh` is always a starting point for someone starting to dig into a recipe; the problem is that there are currently 126 of them, and none can be called more exemplary than any other. Those in `egs/wsj/s5/` are too not special, except for these two special subdirectories: this is just a historical layout artifact.

Having said that, the [Google Style guidelines](https://google.github.io/styleguide/cppguide.html#Implementation_Comment_Donts) (read "Don'ts" and "Punctuation, Spelling, and Grammar" subsections, they apply to all languages) call for comments that are complete sentences, and are capitalized and punctuated as such. I admit that this rule is violated more often than completely observed in our codebase. Your PR in indeed welcome and acceptable, but if improving comments, let's do it right. I'm adding a proposed change where the coding standard is not followed, just to give an example that follows the Guide to a comma. You can just accept them in GitHub interface if you agree. General points for commenting:

 * Write a full sentence, starting with a capital letter and ending with a period. Imperative mood ("Train a model") is the most concise and preferred for a one-sentence comment: code _commands_ the computer to do things, and a comment explains the command, but it's still a command. This is not hard-and-fast rule, just a recommendation; context is important.
 * Add one space between a comment character and text.
 * Wrap lines at 70-80 characters,  exceed 80, and remove end-of-line space.

2022-04-15 19:17 UTC, kkm000 commented on egs/aishell/s5/run.sh
> +# align tri2 [delta+delta-deltas]
```suggestion
# Align training data with the tri2 model.
```
(move the feature type to the point where the tri2 model is trained)

2022-04-15 19:17 UTC, kkm000 commented on egs/aishell/s5/run.sh
> +# train tri3a [LDA+MLLT (second triphone pass)]
```suggestion
# Train the second triphone pass model tri3a on LDA+MLLT features.
```

2022-04-15 19:17 UTC, kkm000 commented on egs/aishell/s5/run.sh
> +# decode tri3a
```suggestion
# Run a test decode with the tri3a model.
```

2022-04-15 19:17 UTC, kkm000 commented on egs/aishell/s5/run.sh
> +# From now, we start building a more serious system with Speaker Adaptive Training(SAT)
```suggestion
# Train the third triphone pass model tri4a on LDA+MLLT+SAT features.
# From now on, we start building a more serious system with Speaker
# Adaptive Training (SAT).```

2022-05-18 14:28 UTC, jtrmal commented
@HuangruiChu I wonder if you could find time to address these comments?

2022-05-20 14:04 UTC, kkm000 commented
LGTM, and thanks! If you ever want to look into improving comments, the common scripts are of a higher priority than individual egs.

2022-05-20 14:04 UTC, kkm000 approved these changes

2022-05-20 14:05 UTC, merged